

import streamlit as st
import pandas as pd
from datetime import datetime
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parents[2]
csv_file = BASE_DIR / "data" / "energy_log.csv"

df = pd.read_csv(csv_file)

with st.sidebar:

    st.image(
        "https://cdn-icons-png.flaticon.com/512/1048/1048953.png",
        width=80
    )

    st.title("Smart Home")

    st.success("System Online")

    st.markdown("---")

    st.write("⚡ Live Monitoring")
    st.write("📊 Analytics")
    st.write("🤖 AI Advisor")
    st.write("📄 Reports")


st.set_page_config(
    page_title="Reports",
    page_icon="📄",
    layout="wide"
)

st.title("📄 Reports & Export Center")

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]

csv_file = BASE_DIR / "data" / "energy_log.csv"

df = pd.read_csv(csv_file)

# ==================================
# SUMMARY
# ==================================

st.subheader("📈 Report Summary")

total_energy = round(df["Energy"].max(), 4)
peak_power = round(df["Power"].max(), 2)
avg_power = round(df["Power"].mean(), 2)
total_cost = round(df["Cost"].max(), 2)

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "⚡ Total Energy",
    f"{total_energy} kWh"
)

c2.metric(
    "🔥 Peak Power",
    f"{peak_power} W"
)

c3.metric(
    "📊 Avg Power",
    f"{avg_power} W"
)

c4.metric(
    "💰 Total Cost",
    f"₹ {total_cost}"
)

st.divider()

# ==================================
# REPORT TABLE
# ==================================

st.subheader("📋 Complete Energy Logs")

st.dataframe(
    df,
    use_container_width=True
)

st.divider()

# ==================================
# CSV DOWNLOAD
# ==================================

st.subheader("⬇ Download CSV Report")

csv = df.to_csv(index=False)

st.download_button(
    label="📥 Download CSV",
    data=csv,
    file_name="energy_report.csv",
    mime="text/csv"
)

st.divider()

# ==================================
# SIMPLE REPORT
# ==================================

st.subheader("📝 Generated Report")

report_text = f"""
SMART HOME ENERGY MONITORING REPORT

Generated On:
{datetime.now()}

-----------------------------------

Total Energy Used:
{total_energy} kWh

Peak Power:
{peak_power} W

Average Power:
{avg_power} W

Estimated Cost:
₹ {total_cost}

-----------------------------------

System Status:
Operational

Generated by:
Smart Home Energy Monitoring Platform
"""

st.text_area(
    "Report Preview",
    report_text,
    height=300
)

st.download_button(
    "📄 Download Text Report",
    report_text,
    file_name="energy_summary.txt"
)

st.markdown("---")

st.markdown("""
<div style='text-align:center;color:gray;'>

Smart Home Energy Monitoring Platform

Built using ESP32 • Wokwi • PlatformIO • Streamlit • Python

</div>
""", unsafe_allow_html=True)